const urls = {
    LOGIN: 'auth/login',
    REGISTER: 'auth/register',
    USERS: 'users',
    GET_PROFILE: 'get-profile',
    UPLOAD: 'v2/upload',
    UPDATE_PROFILE: 'update-profile',
    UPDATE_PROFILE_IMAGE: 'update-profile-image',
    TECHNOLOGIES: 'technologies',
    GET_ALL_USERS: 'get-all-users',
    FREETIME: 'freetime',
    CREATE_FREE_TIME: 'create-free-time',
    GET_FREE_TIME: 'get-free-time',
    DELETE_FREE_TIME: 'delete-free-time',
    GROUP_CHAT: 'chat-groups',
    USER: 'user',
    MESSAGES: 'messages',
    GROUP: 'group',
    POSTS: 'posts',
    POST: 'post',
    CREATE_NEW_POST: 'create-new-post',
    GET_ALL_BLOG: 'get-all-post',
    BOOKING: 'booking',
    JOB_TITLE: 'jobTitle',
    GET_POST_BY_SLUG: 'get-post-by-slug',
    COMMENTS: 'comments',
    DELETE_POST: 'delete-post',
    UPDATE_POST: 'update-post',
    FREETIME_DETAILS: 'freetimeDetails',
    NOTIFICATIONS: 'notifications',
    REVIEWS: 'reviews',
    UPDATE_RATING: 'update-rating',
    PAYMENT: 'payment',
    CREATE_PAYMENT: 'create-payment',
    ME: 'me',
    SEARCH: 'search',
    TRANSFER: 'transfer',
    TRANSACTIONS: 'transactions',
};

export default urls;
