'use client';
// import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import '@/styles/styles.scss';
import { Toaster } from 'sonner';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const roboto = Roboto({
    subsets: ['latin'],
    weight: ['400', '500', '700'],
});

// export const metadata: Metadata = {
//     title: 'Mentor and mentee',
//     description: 'Generated by create next app',
//     icons: {
//         icon: '/favicon.ico',
//     },
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={roboto.className}>
                <Toaster richColors />
                <div>
                    <Header />
                    <div className="pt-[7rem]"> {children}</div>
                    <Footer />
                </div>
            </body>
        </html>
    );
}
