import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from './components/Header';
import Sider from './components/Sider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Mentor and mentee',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Header />
                <div className="flex pt-[8rem]">
                    <Sider />
                    <div className="w-full pl-[10rem] pr-[1rem]">
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
